#!/usr/bin/env python3
"""
Genera data/corpus_sintetico_provisional.csv
200 casos sintéticos (82 Sistemas, 64 Operaciones, 54 Soporte Técnico)
en español rioplatense, sin PII real (tokens [HOST], [PERSONA], [EMAIL]).
"""
import csv
import pathlib

BASE = pathlib.Path(__file__).parent.parent

casos = [
    # === SISTEMAS (82 casos) ===
    ("S001", "el servidor principal no levanta desde esta manana, reiniciamos dos veces y nada", "Sistemas"),
    ("S002", "no puedo conectarme a internet desde mi puesto, el resto del piso tampoco tiene red", "Sistemas"),
    ("S003", "la base de datos del ERP cayó y no podemos facturar, es urgente", "Sistemas"),
    ("S004", "alguien accedió a la carpeta compartida de recursos humanos sin tener permiso, necesito que lo revisen", "Sistemas"),
    ("S005", "el firewall está bloqueando el acceso al portal de proveedores y no sé por qué", "Sistemas"),
    ("S006", "[HOST] no responde hace dos horas y tenemos varios servicios caídos encima", "Sistemas"),
    ("S007", "se cayó la VPN y no puedo trabajar desde casa, ya intenté reconectarme varias veces", "Sistemas"),
    ("S008", "el switch del piso 4 parece que se colgó, varios equipos sin red", "Sistemas"),
    ("S009", "se perdió la conexión al servidor de archivos y perdimos trabajo sin guardar", "Sistemas"),
    ("S010", "necesito que activen el puerto de red del nuevo puesto de trabajo que instalamos ayer", "Sistemas"),
    ("S011", "el sistema de monitoreo de servidores mandó alertas toda la noche pero nadie las vio", "Sistemas"),
    ("S012", "la base de datos de producción tiene el disco casi lleno, me avisaron que está al 95%", "Sistemas"),
    ("S013", "hay un ransomware en la red, detectamos archivos encriptados en varios equipos", "Sistemas"),
    ("S014", "el backup nocturno falló tres noches seguidas y nadie había notado", "Sistemas"),
    ("S015", "el certificado SSL del portal de clientes venció y los usuarios no pueden entrar", "Sistemas"),
    ("S016", "el servidor de correo interno está rechazando los mails entrantes desde ayer a la tarde", "Sistemas"),
    ("S017", "detectaron un ataque de fuerza bruta contra el panel de administración, ya bloquearon la IP pero quieren que lo revisen", "Sistemas"),
    ("S018", "la replicación entre la base de datos primaria y la secundaria se rompió hace varios días", "Sistemas"),
    ("S019", "el servidor [HOST] se reinició solo esta madrugada y no sé si fue una actualización o un problema", "Sistemas"),
    ("S020", "necesito acceso de lectura a la base de datos de analytics para un informe urgente", "Sistemas"),
    ("S021", "el servicio de directorio activo no autentica usuarios desde las 9am, todo el mundo bloqueado", "Sistemas"),
    ("S022", "se cayó el nodo 2 del cluster de alta disponibilidad y quedó corriendo en modo degradado", "Sistemas"),
    ("S023", "el antivirus corporativo no se actualizó en los equipos del área de contabilidad", "Sistemas"),
    ("S024", "la red wifi de la sala de reuniones no funciona y tenemos visitas en una hora", "Sistemas"),
    ("S025", "el servidor de bases de datos tiene la CPU al 100% y no sé qué proceso lo está consumiendo", "Sistemas"),
    ("S026", "nos bloquearon el acceso a ciertos sitios que necesitamos para trabajar, no entiendo la restricción", "Sistemas"),
    ("S027", "hay fuga de memoria en el servidor de aplicaciones y se está poniendo lento todo", "Sistemas"),
    ("S028", "el router del edificio secundario se reinició y dejó sin conectividad a 30 personas", "Sistemas"),
    ("S029", "no podemos hacer consultas a la base de datos de clientes, dice que superó el límite de conexiones", "Sistemas"),
    ("S030", "los logs del servidor de correo muestran intentos de acceso desde IPs de otro país", "Sistemas"),
    ("S031", "el servidor de desarrollo quedó inaccesible después del mantenimiento del fin de semana", "Sistemas"),
    ("S032", "la red de laboratorio está completamente separada de la red corporativa y no debería estarlo", "Sistemas"),
    ("S033", "la contraseña del administrador de base de datos venció y nadie tiene acceso para resetearla", "Sistemas"),
    ("S034", "cayó el servicio de DNS interno y los equipos no pueden resolver nombres de host", "Sistemas"),
    ("S035", "hay un proceso en [HOST] que consume toda la memoria y tira abajo los demás servicios", "Sistemas"),
    ("S036", "nos dimos cuenta que un ex empleado todavía tiene acceso activo al servidor de archivos", "Sistemas"),
    ("S037", "el sistema de monitoreo está mostrando latencia de 900ms en la red interna, claramente algo está mal", "Sistemas"),
    ("S038", "no puedo conectarme remotamente al servidor de producción, la clave SSH ya no funciona", "Sistemas"),
    ("S039", "el servidor de actualizaciones de software está caído y los equipos no pueden parchear", "Sistemas"),
    ("S040", "tengo que migrar la base de datos a un servidor nuevo y necesito ayuda con el proceso", "Sistemas"),
    ("S041", "el almacenamiento en red NAS está mostrando errores de escritura, puede que haya un disco fallando", "Sistemas"),
    ("S042", "la herramienta de gestión de vulnerabilidades detectó un CVE crítico en el middleware", "Sistemas"),
    ("S043", "nos quedamos sin IPs disponibles en el rango DHCP del piso 2", "Sistemas"),
    ("S044", "el servidor de impresión cayó y nadie puede imprimir en toda la empresa", "Sistemas"),
    ("S045", "hay tráfico sospechoso saliendo de un equipo de administración hacia una IP desconocida", "Sistemas"),
    ("S046", "el balanceador de carga dejó de distribuir correctamente y todo va a un solo nodo", "Sistemas"),
    ("S047", "el servidor de archivos compartidos [HOST] responde muy lento, está tardando minutos en abrir carpetas", "Sistemas"),
    ("S048", "se configuró mal una regla del firewall y ahora nadie puede acceder al portal de facturación", "Sistemas"),
    ("S049", "cayeron los servicios en el datacenter secundario y el failover automático no funcionó", "Sistemas"),
    ("S050", "la red inalámbrica de la planta baja tiene interferencia y se desconecta constantemente", "Sistemas"),
    ("S051", "el servidor proxy no está dejando pasar las actualizaciones automáticas del sistema operativo", "Sistemas"),
    ("S052", "me cambiaron el equipo y necesito que me den acceso al servidor de archivos igual que antes", "Sistemas"),
    ("S053", "el servicio de autenticación de dos factores no manda los SMS desde ayer a la noche", "Sistemas"),
    ("S054", "el sistema de videoconferencia no puede conectarse al servidor externo de señalización", "Sistemas"),
    ("S055", "hay dos usuarios con el mismo nombre de cuenta en directorio activo y uno no puede entrar", "Sistemas"),
    ("S056", "el servidor de bases de datos se está quedando lento y los timeouts están aumentando", "Sistemas"),
    ("S057", "la replicación de archivos entre los dos sitios se detuvo y el sitio de contingencia está desactualizado", "Sistemas"),
    ("S058", "tenemos que renovar los certificados de los servidores internos antes del viernes que viene", "Sistemas"),
    ("S059", "los registros de auditoría del servidor muestran accesos fuera de horario que nadie reconoce", "Sistemas"),
    ("S060", "el servidor [HOST] tiene el disco de sistema al 98% y puede fallar en cualquier momento", "Sistemas"),
    ("S061", "el servicio de time sync (NTP) está fallando y los logs de varios sistemas muestran timestamps incorrectos", "Sistemas"),
    ("S062", "el API gateway no está enrutando las peticiones al microservicio correcto después de la última actualización", "Sistemas"),
    ("S063", "se detectó una conexión abierta desde la red interna al exterior por un puerto no estándar", "Sistemas"),
    ("S064", "el servidor de logs centralizados dejó de recibir eventos de varios agentes", "Sistemas"),
    ("S065", "necesito revisar qué puertos están abiertos en el servidor expuesto a internet, hay una auditoría pronto", "Sistemas"),
    ("S066", "el gestor de contraseñas corporativo no sincroniza desde hace dos días", "Sistemas"),
    ("S067", "hay una alarma de temperatura alta en la sala de servidores pero el aire acondicionado parece funcionar", "Sistemas"),
    ("S068", "el módulo de inventario del ERP no puede conectarse a la base de datos, dice connection refused", "Sistemas"),
    ("S069", "el acceso remoto por escritorio (RDP) al servidor de contabilidad dejó de funcionar de golpe", "Sistemas"),
    ("S070", "el script de backup que corre a las 2am está fallando con un error de permisos que no entiendo", "Sistemas"),
    ("S071", "cayó la conectividad entre la sede central y la sucursal, llevamos tres horas sin poder trabajar juntos", "Sistemas"),
    ("S072", "el servidor de autenticación LDAP no responde y nadie puede loguearse en los sistemas internos", "Sistemas"),
    ("S073", "el firewall de aplicaciones web (WAF) está bloqueando peticiones legítimas de nuestros clientes", "Sistemas"),
    ("S074", "el servicio de monitoreo detectó un pico de CPU en cinco servidores al mismo tiempo a medianoche", "Sistemas"),
    ("S075", "necesitamos aumentar el espacio en el volumen de la base de datos de archivos históricos", "Sistemas"),
    ("S076", "el sistema de ticketing cayó y no podemos registrar nuevos incidentes, paradoja total", "Sistemas"),
    ("S077", "el servidor de base de datos tiene una tabla con cientos de millones de filas y las consultas tardan media hora", "Sistemas"),
    ("S078", "el acceso por VPN del equipo externo que hace el mantenimiento del software dejó de funcionar", "Sistemas"),
    ("S079", "el servidor de video vigilancia no está grabando desde hace dos días, nadie se había dado cuenta", "Sistemas"),
    ("S080", "el repositorio git corporativo está inaccesible y el equipo de desarrollo no puede hacer push", "Sistemas"),
    ("S081", "hay un proceso zombie en el servidor que no se puede matar y está bloqueando recursos", "Sistemas"),
    ("S082", "el certificado de autenticación de la VPN venció y todos los usuarios remotos están cortados", "Sistemas"),
    # === OPERACIONES (64 casos) ===
    ("O001", "el proceso de cierre mensual no se puede ejecutar porque el módulo de planificación tiene un error", "Operaciones"),
    ("O002", "nadie me avisó que cambiaron el procedimiento para solicitar días por enfermedad y me mandaron un mail tarde", "Operaciones"),
    ("O003", "el sistema de gestión de turnos está caído y hay cola acumulada en recepción", "Operaciones"),
    ("O004", "necesito que me expliquen el nuevo proceso de aprobación de compras, cambió la semana pasada y no entiendo nada", "Operaciones"),
    ("O005", "el informe de continuidad del negocio para la reunión del jueves todavía no está generado", "Operaciones"),
    ("O006", "el servicio de planificación de recursos no refleja las últimas modificaciones del presupuesto", "Operaciones"),
    ("O007", "el sistema de gestión de contratos no está mandando las alertas de vencimiento automático", "Operaciones"),
    ("O008", "el proceso de alta de nuevo proveedor lleva más de dos semanas parado esperando aprobación", "Operaciones"),
    ("O009", "el dashboard de indicadores operativos muestra datos del mes pasado, no los actualizó", "Operaciones"),
    ("O010", "no puedo acceder al módulo de planificación de la demanda, me dice que no tengo permisos", "Operaciones"),
    ("O011", "el flujo de aprobación de gastos se cortó en el paso de gerencia y nadie sabe quién tiene que seguir", "Operaciones"),
    ("O012", "el sistema de gestión de servicios compartidos no está procesando las solicitudes de los últimos dos días", "Operaciones"),
    ("O013", "me mandaron a una capacitación de un proceso que ya no existe, quién actualiza esas cosas?", "Operaciones"),
    ("O014", "el módulo de planning de producción no considera las restricciones de capacidad que cargamos la semana pasada", "Operaciones"),
    ("O015", "el proceso de conciliación entre áreas tarda una semana y ya empezamos a tener inconsistencias", "Operaciones"),
    ("O016", "el plan de continuidad operativa del área no fue actualizado en dos años y hay una auditoría interna", "Operaciones"),
    ("O017", "la herramienta de gestión de riesgos operativos no deja cargar nuevos eventos desde ayer", "Operaciones"),
    ("O018", "el workflow de aprobación de vacaciones está roto, las solicitudes llegan pero no se pueden aprobar", "Operaciones"),
    ("O019", "el servicio de atención al cliente interno no registró las consultas de la semana pasada", "Operaciones"),
    ("O020", "el módulo de SLA tracking muestra todos los tickets como vencidos aunque no lo están", "Operaciones"),
    ("O021", "nos llegó una auditoría de procesos y no encontramos el documento de procedimiento actualizado para ningún área", "Operaciones"),
    ("O022", "el sistema de planificación de proyectos no está sincronizando con el módulo de recursos humanos", "Operaciones"),
    ("O023", "el proceso de onboarding de nuevos empleados no tiene un responsable claro desde que se fue [PERSONA]", "Operaciones"),
    ("O024", "el módulo de gestión de proveedores no está generando los reportes de desempeño del trimestre", "Operaciones"),
    ("O025", "el proceso de aprobación de órdenes de compra tiene un cuello de botella en la segunda firma y todo está frenado", "Operaciones"),
    ("O026", "el servicio de despacho no puede acceder al sistema de seguimiento de envíos", "Operaciones"),
    ("O027", "el módulo de costeo de procesos muestra valores negativos para varios centros de costo", "Operaciones"),
    ("O028", "el proceso de actualización del mapa de riesgos operativos no se completó antes del cierre del trimestre", "Operaciones"),
    ("O029", "la herramienta de gestión de calidad no envía las notificaciones de auditorías programadas", "Operaciones"),
    ("O030", "el proceso de facturación interna entre áreas está parado porque el sistema no acepta las tarifas nuevas", "Operaciones"),
    ("O031", "el módulo de gestión de capacidad del call center no muestra las métricas de hoy", "Operaciones"),
    ("O032", "hay discrepancias entre el sistema de operaciones y el ERP en los inventarios del cierre del mes", "Operaciones"),
    ("O033", "el proceso de escalado de incidentes críticos no funcionó en el incidente del martes, nadie fue notificado", "Operaciones"),
    ("O034", "la herramienta de gestión de acuerdos de nivel de servicio no está calculando bien los tiempos de resolución", "Operaciones"),
    ("O035", "el módulo de gestión de la continuidad del negocio no refleja el nuevo árbol de decisiones que aprobaron", "Operaciones"),
    ("O036", "el sistema de seguimiento de objetivos (OKR) está mostrando metas del año pasado para varios equipos", "Operaciones"),
    ("O037", "el proceso de resolución de conflictos entre áreas no tiene documentado el nuevo escalado a partir de octubre", "Operaciones"),
    ("O038", "el módulo de gestión de turnos del área de operaciones no reconoce las guardias especiales del fin de año", "Operaciones"),
    ("O039", "el informe de gestión semanal no se generó porque el módulo de consolidación falló", "Operaciones"),
    ("O040", "la herramienta de planificación de la demanda está usando datos de entrada que no fueron validados", "Operaciones"),
    ("O041", "el módulo de aprobación de proyectos tiene una solicitud trabada hace 15 días sin que nadie la vea", "Operaciones"),
    ("O042", "el proceso de rendición de gastos de viaje tarda más de un mes y el área de finanzas se queja", "Operaciones"),
    ("O043", "el sistema de gestión de incidentes operativos no categorizó bien tres eventos del mes pasado", "Operaciones"),
    ("O044", "el módulo de planificación de mantenimiento preventivo no tiene cargado el calendario de paradas del año próximo", "Operaciones"),
    ("O045", "el proceso de entrega de materiales entre almacenes no tiene un responsable de coordinación asignado", "Operaciones"),
    ("O046", "el sistema de seguimiento de KPIs operativos no está leyendo los datos del sistema de producción", "Operaciones"),
    ("O047", "hay una diferencia en los registros del módulo de operaciones compartidas y no encuentro el origen", "Operaciones"),
    ("O048", "el proceso de revisión periódica del mapa de procesos críticos está vencido hace tres meses", "Operaciones"),
    ("O049", "la herramienta de gestión del servicio no identificó correctamente el impacto del incidente de ayer", "Operaciones"),
    ("O050", "el módulo de gestión de cambios operativos no envió la notificación a los responsables del área afectada", "Operaciones"),
    ("O051", "el proceso de solicitud de habilitaciones operativas está documentado en un lugar y se ejecuta en otro", "Operaciones"),
    ("O052", "el sistema de planificación no refleja las restricciones de operación del fin de semana largo", "Operaciones"),
    ("O053", "el módulo de reporting operativo no genera el informe semanal en el formato que pide la gerencia", "Operaciones"),
    ("O054", "el proceso de escalado de desvíos de producción no tiene responsable asignado para el turno noche", "Operaciones"),
    ("O055", "el sistema de monitoreo de acuerdos de nivel de servicio no descargó los datos del último período", "Operaciones"),
    ("O056", "el módulo de gestión de reclamos internos entre áreas está mostrando estados incorrectos", "Operaciones"),
    ("O057", "el proceso de actualización del plan de contingencia del área fue postergado por tercera vez", "Operaciones"),
    ("O058", "el sistema de tracking de compromisos inter-área no registró los acuerdos de la reunión del miércoles", "Operaciones"),
    ("O059", "el módulo de gestión de servicios compartidos tiene configuraciones del año pasado que ya no aplican", "Operaciones"),
    ("O060", "el proceso de aprobación de excepciones operativas no tiene claro quién puede autorizar en ausencia del gerente", "Operaciones"),
    ("O061", "hay un proceso que no tiene dueño asignado desde la reorganización del área y nadie lo está ejecutando", "Operaciones"),
    ("O062", "el sistema de planificación estratégica no integra los cambios que hicimos en el modelo operativo", "Operaciones"),
    ("O063", "el módulo de gestión de proyectos compartidos no tiene visibilidad de los recursos comprometidos en otros proyectos", "Operaciones"),
    ("O064", "la herramienta de seguimiento de acciones correctivas no envía recordatorios cuando se acercan los vencimientos", "Operaciones"),
    # === SOPORTE TÉCNICO (54 casos) ===
    ("ST001", "la computadora de mi escritorio no enciende, la enchufo y nada", "Soporte Técnico"),
    ("ST002", "se me rompió el teclado, una tecla se quedó pegada y no puedo escribir bien", "Soporte Técnico"),
    ("ST003", "el mouse no funciona, ya probé en otro puerto USB y tampoco", "Soporte Técnico"),
    ("ST004", "la pantalla del monitor está parpadeando y me duele la vista trabajar así", "Soporte Técnico"),
    ("ST005", "mi notebook tiene la batería inflada, se ve que empuja la parte de abajo del plástico", "Soporte Técnico"),
    ("ST006", "instalé una actualización de Windows y ahora el equipo tarda 15 minutos en arrancar", "Soporte Técnico"),
    ("ST007", "el software de gestión documental que uso todos los dias se cierra solo después de 5 minutos", "Soporte Técnico"),
    ("ST008", "necesito que me instalen el Adobe Acrobat porque tengo que firmar documentos PDF", "Soporte Técnico"),
    ("ST009", "el lector de código de barras del puesto de caja dejó de leer correctamente", "Soporte Técnico"),
    ("ST010", "la impresora de mi área no aparece en la lista de impresoras disponibles", "Soporte Técnico"),
    ("ST011", "mi computadora mostró una pantalla azul y se reinició, perdí todo lo que estaba haciendo", "Soporte Técnico"),
    ("ST012", "el micrófono del headset no funciona bien en las videoconferencias, me dicen que no me escuchan", "Soporte Técnico"),
    ("ST013", "necesito acceso remoto a mi equipo de la oficina porque voy a trabajar desde casa esta semana", "Soporte Técnico"),
    ("ST014", "se me olvidó la contraseña del sistema de facturación y no puedo entrar", "Soporte Técnico"),
    ("ST015", "el escáner de documentos del área de legajos no está siendo reconocido por ninguna computadora", "Soporte Técnico"),
    ("ST016", "mi notebook se sobrecalienta mucho y se apaga sola cuando trabajo mucho rato", "Soporte Técnico"),
    ("ST017", "el programa de contabilidad dice que la licencia venció pero yo tenía licencia hasta fin de año", "Soporte Técnico"),
    ("ST018", "no puedo abrir los archivos xlsx que me mandan, me dice que el formato no es compatible", "Soporte Técnico"),
    ("ST019", "la cámara web del equipo no funciona y tengo una reunión virtual en media hora", "Soporte Técnico"),
    ("ST020", "necesito que me borren los archivos temporales porque la computadora está muy lenta y el disco lleno", "Soporte Técnico"),
    ("ST021", "el Excel se trabó con una planilla grande y no respondía más, lo cerré y cuando abrí el archivo estaba vacío", "Soporte Técnico"),
    ("ST022", "el auricular bluetooth no se conecta a la laptop, antes funcionaba bien", "Soporte Técnico"),
    ("ST023", "el touchpad de mi notebook está haciendo cosas raras, el cursor se mueve solo", "Soporte Técnico"),
    ("ST024", "instalé un programa que me pidió un compañero y ahora la computadora está lenta y tiene publicidades", "Soporte Técnico"),
    ("ST025", "la impresora de etiquetas del depósito imprime borroso y las etiquetas no pasan bien por el lector", "Soporte Técnico"),
    ("ST026", "mi cuenta de correo no está sincronizando los mails nuevos desde ayer a la mañana", "Soporte Técnico"),
    ("ST027", "la computadora del puesto de guardia no tiene conexión a internet y necesitan consultar la lista de visitantes", "Soporte Técnico"),
    ("ST028", "el software de turno médico se congela cuando intento cargar más de 10 pacientes", "Soporte Técnico"),
    ("ST029", "necesito instalar el cliente VPN en mi notebook personal para conectarme desde casa", "Soporte Técnico"),
    ("ST030", "el equipo del recepcionista tiene la pantalla rayada y ya no se puede leer bien", "Soporte Técnico"),
    ("ST031", "me llegó un mail sospechoso que me pide que ingrese mis credenciales corporativas, qué hago?", "Soporte Técnico"),
    ("ST032", "el software de firma digital no reconoce el token USB que tengo", "Soporte Técnico"),
    ("ST033", "la notebook que uso para presentaciones no tiene la entrada HDMI que necesito para el proyector", "Soporte Técnico"),
    ("ST034", "necesito recuperar un archivo que borré sin querer de mi escritorio la semana pasada", "Soporte Técnico"),
    ("ST035", "el equipo de la sala de reuniones se quedó sin sonido después de que alguien actualizó algo", "Soporte Técnico"),
    ("ST036", "mi contraseña de Windows venció y el sistema no me deja cambiarla por ninguna que yo ingrese", "Soporte Técnico"),
    ("ST037", "el programa de facturación electrónica no puede conectarse al servicio de AFIP y da error de certificado", "Soporte Técnico"),
    ("ST038", "la impresora multifunción del área de marketing está atascada y no se puede desatascar sola", "Soporte Técnico"),
    ("ST039", "me cambiaron el equipo y no me migraron los favoritos del navegador ni los archivos del escritorio", "Soporte Técnico"),
    ("ST040", "el proyector de la sala B no enciende y hay una capacitación en 40 minutos", "Soporte Técnico"),
    ("ST041", "necesito que me amplíen el espacio en el correo, llevo meses con el buzón lleno y borrando todo", "Soporte Técnico"),
    ("ST042", "la notebook nueva que me entregaron no tiene instalado el paquete de Office", "Soporte Técnico"),
    ("ST043", "el lector de huella dactilar del equipo de entrada al edificio no reconoce a tres empleados", "Soporte Técnico"),
    ("ST044", "el software de diseño que uso para los folletos perdió todas las fuentes tipográficas después de una actualización", "Soporte Técnico"),
    ("ST045", "la pantalla de la notebook tiene una línea vertical verde que apareció sola esta mañana", "Soporte Técnico"),
    ("ST046", "mi equipo no puede imprimir en doble faz aunque la impresora lo soporta", "Soporte Técnico"),
    ("ST047", "el antivirus del equipo está bloqueando una aplicación que necesito usar para trabajar", "Soporte Técnico"),
    ("ST048", "la conexión WiFi de mi notebook se cae cada 20 minutos y tengo que reconectarme", "Soporte Técnico"),
    ("ST049", "necesito hacer una videoconferencia con alguien de afuera pero el sistema no me deja invitar externos", "Soporte Técnico"),
    ("ST050", "el equipo del nuevo ingresante todavía no tiene configurado el correo corporativo y ya lleva una semana", "Soporte Técnico"),
    ("ST051", "el software de control de stock no cierra correctamente y cada vez que lo abro dice que hubo un cierre inesperado", "Soporte Técnico"),
    ("ST052", "la computadora de recepción se pone muy lenta a partir de las 10am y hay que reiniciarla todos los días", "Soporte Técnico"),
    ("ST053", "el disco externo de backup personal no es reconocido por el equipo, ya probé varios puertos", "Soporte Técnico"),
    ("ST054", "el teclado numérico no funciona aunque el numlock está activado", "Soporte Técnico"),
]

out = BASE / "data" / "corpus_sintetico_provisional.csv"
out.parent.mkdir(exist_ok=True)
with open(out, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f, quoting=csv.QUOTE_ALL)
    writer.writerow(["id", "descripcion", "categoria_real"])
    for row in casos:
        writer.writerow(row)

print(f"Escrito: {out}")
print(f"Filas: {len(casos)}")
